CREATE DATABASE IF NOT EXISTS userdb;
CREATE DATABASE IF NOT EXISTS postdb;
CREATE DATABASE IF NOT EXISTS likedb;
CREATE DATABASE IF NOT EXISTS commentdb;
CREATE DATABASE IF NOT EXISTS followdb;
CREATE DATABASE IF NOT EXISTS searchdb;
CREATE DATABASE IF NOT EXISTS notificationdb;
