server:
  port: 9090

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/posts/**

        - id: like-service
          uri: lb://like-service
          predicates:
            - Path=/api/likes/**

        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/api/comments/**

        - id: follow-service
          uri: lb://follow-service
          predicates:
            - Path=/api/follows/**

        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/api/search/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/